apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch-admin.fullname" . }}
  labels:
    {{- include "elasticsearch-admin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.updateStrategy.type | quote }}
  selector:
    matchLabels:
      {{- include "elasticsearch-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "elasticsearch-admin.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        supplementalGroups:
          - 5051
          - 1000
          - 206
          - 0
      serviceAccountName: default
    {{- if .Values.affinity }}
      affinity:
        podAntiAffinity:
          {{ .Values.affinity }}:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ include "elasticsearch-admin.fullname" . | quote }}
                topologyKey: "kubernetes.io/hostname"
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry.url }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          securityContext:
          {{- if index .Values "securityContext" }}
            {{- if index .Values "securityContext" "elasticsearchadmin" }}
              {{- toYaml .Values.securityContext.elasticsearchadmin | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            - name: TZ
              value: {{ .Values.global.timezone }}
          resources:
            requests:
{{- if index .Values.resources "elasticsearch-admin" "requests" "memory" }}
              memory: {{ index .Values.resources "elasticsearch-admin" "requests" "memory" | quote }}
{{- end }}
{{- if index .Values.resources "elasticsearch-admin" "requests" "cpu" }}
              cpu: {{ index .Values.resources "elasticsearch-admin" "requests" "cpu" | quote }}
{{- end }}
{{- if index .Values.resources "elasticsearch-admin" "requests" "ephemeral-storage" }}
              ephemeral-storage: {{ index .Values.resources "elasticsearch-admin" "requests" "ephemeral-storage" | quote }}
{{- end }}
            limits:
{{- if index .Values.resources "elasticsearch-admin" "limits" "memory" }}
              memory: {{ index .Values.resources "elasticsearch-admin" "limits" "memory" | quote }}
{{- end }}
{{- if index .Values.resources "elasticsearch-admin" "limits" "cpu" }}
              cpu: {{ index .Values.resources "elasticsearch-admin" "limits" "cpu" | quote }}
{{- end }}
{{- if index .Values.resources "elasticsearch-admin" "limits" "ephemeral-storage" }}
              ephemeral-storage: {{ index .Values.resources "elasticsearch-admin" "requests" "ephemeral-storage" | quote }}
{{- end }}
          volumeMounts:
            - name: exportpath
              mountPath: /ericsson/elect-export-path
           
      {{- if or .Values.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
      {{- if .Values.nodeSelector }}
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
        {{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: exportpath
          persistentVolumeClaim:
            claimName: "{{ .Values.utilityName }}"
{{- if include "elasticsearch-admin.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "elasticsearch-admin.pullSecrets" . }}
{{- end }}
