{{- $g := fromJson (include "elasticsearch-admin.globalMap" .) -}}
{{- if ne $g.securityPolicy.rolekind "" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{ include "elasticsearch-admin.metadata" . | indent 2 }}
{{- if (eq ($g.securityPolicy.rolekind) "Role") }}
  name: {{ .Values.service.name }}-sa-r-{{ .Values.securityPolicy.rolename }}-sp
{{- else }}
  name: {{ .Values.service.name }}-sa-c-{{ .Values.securityPolicy.rolename }}-sp
{{- end }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $g.securityPolicy.rolekind }}
  name: {{ .Values.securityPolicy.rolename }}
subjects:
- kind: ServiceAccount
  name: {{ template "elasticsearch-admin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{ include "elasticsearch-admin.metadata" . | indent 2 }}
  name: {{ template "elasticsearch-admin.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "elasticsearch-admin.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "elasticsearch-admin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

