apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
{{ include "elasticsearch-admin.metadata" . | indent 2 }}
  name: {{ template "elasticsearch-admin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

